services:
  tailnet-labs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PLUGINS: "github.com/caddy-dns/cloudflare"
        ALL_PROXY: ${ALL_PROXY}
        HTTP_PROXY: ${HTTP_PROXY}
        http_proxy: ${http_proxy}
    image: tailnet-labs:latest
    container_name: tailnet-labs
    privileged: true               # gives access to /dev/net/tun
    cap_add:
      - NET_BIND_SERVICE
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      TAILNET_NAME: ${TAILNET_NAME:-tailnet.gnx}
      TAILSCALE_HOSTNAME: ${TAILSCALE_HOSTNAME:-tailnet-labs}
      TAILSCALE_AUTHKEY_FILE: /run/secrets/tailscale_authkey
      CLOUDFLARE_API_TOKEN_FILE: /run/secrets/cloudflare_api_token
      TAILSCALE_STATE: /var/lib/tailscale
    secrets:
      - tailscale_authkey
      - cloudflare_api_token
    volumes:
      - state:/var/lib/tailscale
      - config:/etc/caddy
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "tailscale", "status"]
      interval: 30s
      timeout: 5s
      retries: 3

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    depends_on:
      - tailnet-labs
    volumes:
      - ./state/mnt/data/appdata/jellyfin:/config
      - ./state/mnt/data/media:/data:ro
      - /dev/shm:/transcode
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - JELLYFIN_PublishedServerUrl=jellyfin.${TAILNET_NAME:-tailnet.gnx}
    ports:
      - 2285:8096
    restart: unless-stopped

  abs:
    image: advplyr/audiobookshelf
    container_name: abs
    hostname: abs
    depends_on:
      - tailnet-labs
    volumes:
      - ./state/mnt/data/media/audiobooks/library:/audiobooks:ro
      - ./state/mnt/data/media/audiobooks/podcasts:/podcasts
      - ./state/mnt/data/appdata/audiobookshelf/metadata:/metadata
      - ./state/mnt/data/appdata/audiobookshelf/config:/config
    ports:
      - 2284:80
    restart: unless-stopped

secrets:
  tailscale_authkey:
    file: ./TAILSCALE_AUTHKEY_FILE
  cloudflare_api_token:
    file: ./CLOUDFLARE_API_TOKEN_FILE

volumes:
  state:
  config: