services:
  tailnet-labs:
    image: tailnet-labs:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PLUGINS: "github.com/caddy-dns/cloudflare"
        XCADDY_DEBUG: 1
    privileged: true
    environment:
      - TAILSCALE_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TAILNET_NAME=${TAILNET_NAME}
      - TAILSCALE_HOSTNAME=${TAILSCALE_HOSTNAME}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./tailnet-state:/tailnet
      - ./config:/etc/caddy
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  tailnet-state:
  config:
